# ---------- postgres credentials ----------------- 
database:
  NAME: 'aty_safe'
  USER: 'aty'
  PASSWORD: 'aty1234'
  HOST: 'localhost'  
  PORT: 5432    

admin:
  EMAIL: 'admin@mail.com'
  PASSWORD: 'admin123'