# ---------- postgres credentials ----------------- 
database:
  NAME: 'dbms_db'
  USER: 'postgres'
  PASSWORD: 'postgres'
  HOST: 'localhost'  
  PORT: 5432    

admin:
  EMAIL: 'admin@mail.com'
  PASSWORD: 'admin123'