# Generated by Django 4.2.11 on 2024-05-06 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccounttype_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_no', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_opened', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='user',
        ),
        migrations.CreateModel(
            name='CheckingBankAccount',
            fields=[
                ('bankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.bankaccount')),
                ('service_charge', models.DecimalField(decimal_places=2, default=10.0, max_digits=12)),
            ],
            bases=('accounts.bankaccount',),
        ),
        migrations.CreateModel(
            name='SavingsBankAccount',
            fields=[
                ('bankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.bankaccount')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=8, help_text='Annual interest rate in percentage', max_digits=5)),
            ],
            bases=('accounts.bankaccount',),
        ),
        migrations.DeleteModel(
            name='BankAccountType',
        ),
    ]
