# Generated by Django 4.2.11 on 2024-05-06 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount_remove_userbankaccount_account_type_and_more'),
        ('transactions', '0003_alter_transaction_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
