# Generated by Django 4.2.11 on 2024-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_userbankaccount_bankaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
