# Generated by Django 5.0.4 on 2024-05-03 18:17

import django.db.models.deletion
import loans.models
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States')),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('tenure', models.PositiveIntegerField()),
                ('installment_paid', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('company', models.TextField()),
                ('premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField(null=True)),
                ('last_name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.IntegerField(unique=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.address')),
            ],
        ),
        migrations.CreateModel(
            name='EducationLoan',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loans.loan')),
                ('graduation_date', models.DateField()),
                ('degree', models.TextField()),
                ('college_id', models.TextField()),
                ('student_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.studentinfo')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.university')),
            ],
            bases=('loans.loan',),
        ),
        migrations.CreateModel(
            name='HomeLoan',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loans.loan')),
                ('house_built_year', models.PositiveIntegerField(validators=[loans.models.validate_year])),
                ('home_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_loans', to='loans.address')),
                ('insurance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.insurance')),
            ],
            bases=('loans.loan',),
        ),
    ]
