# Generated by Django 5.0.4 on 2024-05-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='middle_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(),
        ),
    ]
