# Generated by Django 5.0.4 on 2024-05-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_insurance_company_alter_studentinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationloan',
            name='college_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='educationloan',
            name='degree',
            field=models.CharField(),
        ),
    ]
