# Generated by Django 5.0.4 on 2024-05-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_educationloan_college_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=2),
        ),
    ]
