# Generated by Django 4.2.11 on 2024-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_remove_university_address_loan_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
